project_id = "trhpnjrxoysbbigpddkb"

[functions.generate-itinerary]
verify_jwt = false

[functions.generate-activity-detail]
verify_jwt = false

[functions.list-admin-users]
# Uses default verify_jwt = true for authenticated access